#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamGame.Resource", IsApplication=true)]

namespace XamGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060013
			public const int board_padding = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int card_margin = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int clock_height = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int clock_margin_right = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int clock_text_margin_right = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int clock_text_size = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int clock_width = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int difficulty_margin = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int difficulty_margin_top = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int difficulty_padding = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int margine_top = 2131099666;
			
			// aapt resource value: 0x7f06001b
			public const int popup_button_back = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int popup_button_back_bottom = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int popup_button_back_left = 2131099676;
			
			// aapt resource value: 0x7f060028
			public const int popup_button_score_margin_bottom = 2131099688;
			
			// aapt resource value: 0x7f060020
			public const int popup_button_star_margin_1 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int popup_button_star_margin_2 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int popup_button_star_margin_3 = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int popup_button_star_margin_top = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int popup_button_star_size = 2131099678;
			
			// aapt resource value: 0x7f060024
			public const int popup_button_time_height = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int popup_button_time_margin_bottom = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int popup_button_time_margin_right = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int popup_button_time_size = 2131099687;
			
			// aapt resource value: 0x7f060023
			public const int popup_button_time_width = 2131099683;
			
			// aapt resource value: 0x7f06002a
			public const int popup_settings_height = 2131099690;
			
			// aapt resource value: 0x7f06002e
			public const int popup_settings_padding_left = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int popup_settings_padding_top = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int popup_settings_sound_image_size = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int popup_settings_sound_text_size = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int popup_settings_width = 2131099689;
			
			// aapt resource value: 0x7f06001a
			public const int popup_won_height = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int popup_won_width = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int settings_game_button = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int settings_game_button_margin = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int start_game_button = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int start_game_button_lights = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int start_game_button_margin = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int theme_margin = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int theme_padding = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int title_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int title_margin_top = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int title_width = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int tooltip_height = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int tooltip_margin_bottom = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int tooltip_margin_left = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int tooltip_width = 2131099657;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int animals_1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animals_10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int animals_11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int animals_12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int animals_13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int animals_14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int animals_15 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int animals_16 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int animals_17 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int animals_18 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int animals_19 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int animals_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int animals_20 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int animals_21 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int animals_22 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int animals_23 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int animals_24 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int animals_25 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int animals_26 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int animals_27 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int animals_28 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int animals_3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int animals_4 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int animals_5 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int animals_6 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int animals_7 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int animals_8 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int animals_9 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int animals_theme_star_0 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int animals_theme_star_1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int animals_theme_star_2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int animals_theme_star_3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int back_animals = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int back_horror = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int background = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int button_again = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int button_back = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int button_difficulty_1_star_0 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int button_difficulty_1_star_1 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int button_difficulty_1_star_2 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int button_difficulty_1_star_3 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int button_difficulty_2_star_0 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int button_difficulty_2_star_1 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int button_difficulty_2_star_2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int button_difficulty_2_star_3 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int button_difficulty_3_star_0 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int button_difficulty_3_star_1 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int button_difficulty_3_star_2 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int button_difficulty_3_star_3 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int button_difficulty_4_star_0 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int button_difficulty_4_star_1 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int button_difficulty_4_star_2 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int button_difficulty_4_star_3 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int button_difficulty_5_star_0 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int button_difficulty_5_star_1 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int button_difficulty_5_star_2 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int button_difficulty_5_star_3 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int button_difficulty_6_star_0 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int button_difficulty_6_star_1 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int button_difficulty_6_star_2 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int button_difficulty_6_star_3 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int button_google_play = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int button_music_off = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int button_music_on = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int button_rate = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int button_settings = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int button_start = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int button_start_lights = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_launcher = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int icon = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int level_complete = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int level_complete_star = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int monsters_theme_star_0 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int monsters_theme_star_1 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int monsters_theme_star_2 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int monsters_theme_star_3 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int mosters_1 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int mosters_10 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int mosters_11 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int mosters_12 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int mosters_13 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int mosters_14 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int mosters_15 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int mosters_16 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int mosters_17 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int mosters_18 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int mosters_19 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int mosters_2 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int mosters_20 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int mosters_21 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int mosters_22 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int mosters_23 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int mosters_24 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int mosters_25 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int mosters_26 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int mosters_27 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int mosters_28 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int mosters_29 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int mosters_3 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int mosters_30 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int mosters_31 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int mosters_32 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int mosters_33 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int mosters_34 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int mosters_35 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int mosters_36 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int mosters_37 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int mosters_38 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int mosters_39 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int mosters_4 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int mosters_40 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int mosters_5 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int mosters_6 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int mosters_7 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int mosters_8 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int mosters_9 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int settings_popup = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int tile = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int tile_back = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int tile_back_star = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int time_bar = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int title = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int tooltip_play = 2130837626;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int background_image = 2131296256;
			
			// aapt resource value: 0x7f090018
			public const int button_back = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int button_next = 2131296281;
			
			// aapt resource value: 0x7f090001
			public const int fragment_container = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int game_board = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int game_container = 2131296269;
			
			// aapt resource value: 0x7f090011
			public const int google_play_button = 2131296273;
			
			// aapt resource value: 0x7f090022
			public const int image = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int image_top = 2131296291;
			
			// aapt resource value: 0x7f090002
			public const int popup_container = 2131296258;
			
			// aapt resource value: 0x7f090016
			public const int rate = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int rate_text = 2131296279;
			
			// aapt resource value: 0x7f09001d
			public const int score_bar_text = 2131296285;
			
			// aapt resource value: 0x7f090004
			public const int select_difficulty_1 = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int select_difficulty_2 = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int select_difficulty_3 = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int select_difficulty_4 = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int select_difficulty_5 = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int select_difficulty_6 = 2131296265;
			
			// aapt resource value: 0x7f090010
			public const int settings_game_button = 2131296272;
			
			// aapt resource value: 0x7f090014
			public const int sound_image = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int sound_off = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int sound_off_text = 2131296277;
			
			// aapt resource value: 0x7f09001a
			public const int star_1 = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int star_2 = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int star_3 = 2131296284;
			
			// aapt resource value: 0x7f09000f
			public const int start_game_button = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int start_game_button_lights = 2131296270;
			
			// aapt resource value: 0x7f09001f
			public const int theme_animals = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int theme_animals_container = 2131296286;
			
			// aapt resource value: 0x7f090021
			public const int theme_monsters = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int theme_monsters_container = 2131296288;
			
			// aapt resource value: 0x7f09000b
			public const int time_bar_image = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int time_bar_text = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int title = 2131296259;
			
			// aapt resource value: 0x7f090012
			public const int tooltip = 2131296274;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int board_view = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int difficult_view = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int difficulty_select_fragment = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int game_fragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int menu_fragment = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int popup_settings_view = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int popup_won_view = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int theme_select_fragment = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int tile_view = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int background_music = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int correct_answer = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int star = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int debug = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
